version: '3.4'
services:
  nginx:
    container_name: nginx-compose
    image: nginx
    ports:
      - "9999:80"
    volumes: 
      - ".:/"
    # build:
    #   context: .
    #   dockerfile: CShark.Platform.NotificationService/Dockerfile

  # cassandra:
  #   image: cassandra
  #   restart: always