apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosouniversity
  labels:
    app: contosouniversity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contosouniversity
  template:
    metadata:
      labels:
        app: contosouniversity
    spec:
      containers:
        - name: contosouniversity
          image: csharkworkshop.azurecr.io/contosouniversity:v1.1
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred
