apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosouniversity
  labels:
    app: contosouniversity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contosouniversity
  template:
    metadata:
      labels:
        app: contosouniversity
    spec:
      containers:
      - name: contosouniversity
        image: csharkworkshop.azurecr.io/contosouniversity:v5.0
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        env:
          - name: ConnectionStrings__SchoolContext
            valueFrom:
              secretKeyRef:
                key: SchoolContext
                name: connectionstring
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
       - name: regcred