apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4.39
          volumeMounts:
          - readOnly: true
            name: config-volume
            mountPath: /usr/local/apache2/conf/httpd.conf
            subPath: httpd.conf
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
      volumes:
        - name: config-volume
          configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
            name: httpd-conf1