apiVersion: v1
kind: Service
metadata:  
  name: contosouniversity
spec:
  selector:    
    app: contosouniversity
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP