kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contoso-binding
  namespace: test
subjects:
– kind: ServiceAccount
    name: contoso
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer